name: nitsche_clamped_square

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install scikit-fem==1.0.0 jupyter matplotlib

    - name: Initialize results.csv
      run: |
        echo "h,nitsche,trad" > results.csv

    - name: Run 1
      env:
        NREFS: 0
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        jq '[(.cells[2].outputs[0].data."text/plain"[0]|tonumber), (.cells[4].outputs[0].data."text/plain"[0]|tonumber), (.cells[5].outputs[0].data."text/plain"[0]|tonumber)] | @csv' nitsche_clamped_square.ipynb -r >> results.csv

    - name: Run 2
      env:
        NREFS: 1
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        jq '[(.cells[2].outputs[0].data."text/plain"[0]|tonumber), (.cells[4].outputs[0].data."text/plain"[0]|tonumber), (.cells[5].outputs[0].data."text/plain"[0]|tonumber)] | @csv' nitsche_clamped_square.ipynb -r >> results.csv

    - name: Run 3
      env:
        NREFS: 2
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        jq '[(.cells[2].outputs[0].data."text/plain"[0]|tonumber), (.cells[4].outputs[0].data."text/plain"[0]|tonumber), (.cells[5].outputs[0].data."text/plain"[0]|tonumber)] | @csv' nitsche_clamped_square.ipynb -r >> results.csv

    - uses: actions/upload-artifact@v2
      with:
        name: Results
        path: results.csv
