name: nitsche_clamped_square

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install scikit-fem==1.0.0 jupyter matplotlib

    - name: Initialize ex1results.csv
      run: |
        echo "h,nitsche,trad,estimator,nitscheh2,nitschemd" > ex1results.csv

    - name: Run 1
      env:
        NREFS: 0
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        sh extract.sh $NREFS

    - name: Run 2
      env:
        NREFS: 1
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        sh extract.sh $NREFS

    - name: Run 3
      env:
        NREFS: 2
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        sh extract.sh $NREFS

    - name: Run 4
      env:
        NREFS: 3
      run: |
        jupyter nbconvert --to notebook --execute nitsche_clamped_square.ipynb
        sh extract.sh $NREFS

    - uses: actions/upload-artifact@v2
      with:
        name: ex1
        path: ex1*
